###
GET http://localhost:8080/book

###
@isbn = 978-3836211161
GET http://localhost:8080/book/{{isbn}}

###
@author = Rob
GET http://localhost:8080/book?
    author={{author}}

###
POST http://localhost:8080/book/search
Content-Type: application/json

{
  "author": "Birgit",
  "isbn": "978-3836211160"
}

###
POST http://localhost:8080/book
Content-Type: application/json

{
  "isbn": "222-2222222222",
  "title": "My first book",
  "author": "Birgit Kratz",
  "description": "it's just genial"
}