###
GET http://localhost:8080/book

###
@isbn = 978-3836211161
GET http://localhost:8080/book/{{isbn}}

###
@author = Rob
GET http://localhost:8080/book?
    author={{author}}

###
POST http://localhost:8080/book/search
Content-Type: application/json

{
  "author": "Birgit",
  "isbn": "978-3836211160"
}
