server:
  port: 8181

spring:
  datasource:
    url: jdbc:h2:mem:bookshelf
    driver-class-name: org.h2.Driver
    username: user
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  liquibase:
    enabled: false
debug: true